In [4]:
import os
import requests
import pandas as pd 

from dotenv import load_dotenv

In [5]:
df= pd.read_csv("../data/raw/redfin_housing_market_monthly_all_metros_2015_Jan_to_2026_Jul.csv")
print(df.head())

  LAST UPDATED FREQUENCY PERIOD BEGIN  PERIOD END  REGION ID REGION TYPE  \
0   2026-08-03   Monthly   2026-07-01  2026-07-31      10100       Metro
1   2026-08-03   Monthly   2026-07-01  2026-07-31      10140       Metro
2   2026-08-03   Monthly   2026-07-01  2026-07-31      10180       Metro
3   2026-08-03   Monthly   2026-07-01  2026-07-31      10220       Metro
4   2026-08-03   Monthly   2026-07-01  2026-07-31      10300       Metro

               REGION NAME  HOMES SOLD  HOMES SOLD YOY (%)  \
0  Aberdeen, SD metro area        39.0               -0.80
1  Aberdeen, WA metro area       127.0               24.05
2   Abilene, TX metro area       230.0               -5.72
3       Ada, OK metro area        42.0              -11.01
4    Adrian, MI metro area       116.0                0.93

   MEDIAN SALE PRICE NSA ($)  ...  MEDIAN NEW LISTING PRICE ($)  \
0                   287106.0  ...                      314204.0
1                   368353.0  ...                      394731.0
2                   308983.0  ...                      281598.0
3                   214332.0  ...                      206505.0
4                   239255.0  ...                      261837.0

   MEDIAN NEW LISTING PRICE YOY (%)  MEDIAN NEW LISTING PRICE PER SQ.FT. ($)  \
0                              0.79                                   208.22
1                              6.97                                   267.87
2                             18.27                                   172.28
3                             -7.17                                   128.07
4                             11.90                                   166.79

   MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)  \
0                                         0.80
1                                         4.83
2                                        11.91
3                                       -11.09
4                                        17.80

   MEDIAN SALE PRICE PER SQ.FT. ($)  MEDIAN SALE PRICE PER SQ.FT. YOY (%)  \
0                            239.02                                 27.33
1                            243.15                                 -5.62
2                            174.25                                 13.02
3                            121.27                                -12.26
4                            162.49                                 17.16

   MONTHS OF SUPPLY  MONTHS OF SUPPLY YOY (%)  \
0               2.8                    -65.75
1               6.2                    -44.24
2               2.2                    -97.65
3               2.8                    -17.92
4               3.0                      9.95

   PERCENT OFF MARKET IN TWO WEEKS (%)  \
0                                10.29
1                                24.45
2                                54.29
3                                34.93
4                                51.51

   PERCENT OFF MARKET IN TWO WEEKS YOY (PPTS)MEDIAN DAYS ON MARKET YOY (%)
0                                              -8.46
1                                              -8.35
2                                              23.82
3                                              -2.03
4                                              15.42

[5 rows x 35 columns]

In [6]:
df = df.drop(columns={"FREQUENCY","REGION TYPE","HOMES SOLD YOY (%)","MEDIAN SALE PRICE NSA YOY (%)"
,"SHARE SOLD ABOVE ORIGINAL LIST (%)","NEW LISTINGS YOY (%)","NEW LISTINGS YOY (%)"
,"ACTIVE LISTINGS YOY (%)","INVENTORY YOY (%)","PENDING SALES YOY (%)","MEDIAN NEW LISTING PRICE YOY (%)",
"MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)","MEDIAN SALE PRICE PER SQ.FT. YOY (%)","MEDIAN SALE PRICE PER SQ.FT. YOY (%)",
"MONTHS OF SUPPLY YOY (%)","PERCENT OFF MARKET IN TWO WEEKS YOY (PPTS)MEDIAN DAYS ON MARKET YOY (%)"})

In [7]:
df.head()

,LAST UPDATED,PERIOD BEGIN,PERIOD END,REGION ID,REGION NAME,HOMES SOLD,MEDIAN SALE PRICE NSA ($),MEDIAN DAYS ON MARKET (DAYS),Unnamed: 12,AVERAGE SALE TO LIST RATIO (%),...,SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS),NEW LISTINGS,ACTIVE LISTINGS,INVENTORY,PENDING SALES,MEDIAN NEW LISTING PRICE ($),MEDIAN NEW LISTING PRICE PER SQ.FT. ($),MEDIAN SALE PRICE PER SQ.FT. ($),MONTHS OF SUPPLY,PERCENT OFF MARKET IN TWO WEEKS (%)
0,2026-08-03,2026-07-01,2026-07-31,10100,"Aberdeen, SD metro area",39.0,287106.0,71.0,5629.34,95.31,...,-9.49,46.0,171.0,106.0,58.0,314204.0,208.22,239.02,2.8,10.29
1,2026-08-03,2026-07-01,2026-07-31,10140,"Aberdeen, WA metro area",127.0,368353.0,44.0,768.18,96.50,...,-25.18,200.0,895.0,757.0,114.0,394731.0,267.87,243.15,6.2,24.45
2,2026-08-03,2026-07-01,2026-07-31,10180,"Abilene, TX metro area",230.0,308983.0,21.0,-2691.32,98.96,...,18.70,297.0,711.0,486.0,241.0,281598.0,172.28,174.25,2.2,54.29
3,2026-08-03,2026-07-01,2026-07-31,10220,"Ada, OK metro area",42.0,214332.0,13.0,-594.63,99.66,...,13.34,51.0,172.0,114.0,43.0,206505.0,128.07,121.27,2.8,34.93
4,2026-08-03,2026-07-01,2026-07-31,10300,"Adrian, MI metro area",116.0,239255.0,41.0,216.94,99.04,...,3.07,152.0,453.0,339.0,134.0,261837.0,166.79,162.49,3.0,51.51

In [8]:
df.columns

Index(['LAST UPDATED', 'PERIOD BEGIN', 'PERIOD END', 'REGION ID',
       'REGION NAME', 'HOMES SOLD', 'MEDIAN SALE PRICE NSA ($)',
       'MEDIAN DAYS ON MARKET (DAYS)', 'Unnamed: 12',
       'AVERAGE SALE TO LIST RATIO (%)',
       'AVERAGE SALE TO LIST RATIO YOY (PPTS)',
       'SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS)', 'NEW LISTINGS',
       'ACTIVE LISTINGS', 'INVENTORY', 'PENDING SALES',
       'MEDIAN NEW LISTING PRICE ($)',
       'MEDIAN NEW LISTING PRICE PER SQ.FT. ($)',
       'MEDIAN SALE PRICE PER SQ.FT. ($)', 'MONTHS OF SUPPLY',
       'PERCENT OFF MARKET IN TWO WEEKS (%)'],
      dtype='object')

In [9]:
df.shape

(131331, 21)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131331 entries, 0 to 131330
Data columns (total 21 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   LAST UPDATED                               131331 non-null  object
 1   PERIOD BEGIN                               131331 non-null  object
 2   PERIOD END                                 131331 non-null  object
 3   REGION ID                                  131331 non-null  int64
 4   REGION NAME                                131331 non-null  object
 5   HOMES SOLD                                 129578 non-null  float64
 6   MEDIAN SALE PRICE NSA ($)                  129578 non-null  float64
 7   MEDIAN DAYS ON MARKET (DAYS)               129447 non-null  float64
 8   Unnamed: 12                                127879 non-null  float64
 9   AVERAGE SALE TO LIST RATIO (%)             122835 non-null  float64
 10  AVERAGE SALE TO LIST RATIO YOY (PPTS)      119902 non-null  float64
 11  SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS)  128081 non-null  float64
 12  NEW LISTINGS                               130097 non-null  float64
 13  ACTIVE LISTINGS                            131233 non-null  float64
 14  INVENTORY                                  131158 non-null  float64
 15  PENDING SALES                              129461 non-null  float64
 16  MEDIAN NEW LISTING PRICE ($)               130087 non-null  float64
 17  MEDIAN NEW LISTING PRICE PER SQ.FT. ($)    130061 non-null  float64
 18  MEDIAN SALE PRICE PER SQ.FT. ($)           129556 non-null  float64
 19  MONTHS OF SUPPLY                           129501 non-null  float64
 20  PERCENT OFF MARKET IN TWO WEEKS (%)        129461 non-null  float64
dtypes: float64(16), int64(1), object(4)
memory usage: 21.0+ MB

In [11]:
df.isnull().sum()

LAST UPDATED                                     0
PERIOD BEGIN                                     0
PERIOD END                                       0
REGION ID                                        0
REGION NAME                                      0
HOMES SOLD                                    1753
MEDIAN SALE PRICE NSA ($)                     1753
MEDIAN DAYS ON MARKET (DAYS)                  1884
Unnamed: 12                                   3452
AVERAGE SALE TO LIST RATIO (%)                8496
AVERAGE SALE TO LIST RATIO YOY (PPTS)        11429
SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS)     3250
NEW LISTINGS                                  1234
ACTIVE LISTINGS                                 98
INVENTORY                                      173
PENDING SALES                                 1870
MEDIAN NEW LISTING PRICE ($)                  1244
MEDIAN NEW LISTING PRICE PER SQ.FT. ($)       1270
MEDIAN SALE PRICE PER SQ.FT. ($)              1775
MONTHS OF SUPPLY                              1830
PERCENT OFF MARKET IN TWO WEEKS (%)           1870
dtype: int64

In [12]:
df=df.drop(columns={"AVERAGE SALE TO LIST RATIO YOY (PPTS)","SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS)",
"Unnamed: 12","PERIOD END"})

In [13]:
df_missing_price = df[df["MEDIAN SALE PRICE NSA ($)"].isnull()]

In [14]:
df_missing_price[
    [
        "PERIOD BEGIN",
        "REGION ID",
        "REGION NAME",
        "MEDIAN SALE PRICE NSA ($)",
        "HOMES SOLD"
    ]
].head(20)

,PERIOD BEGIN,REGION ID,REGION NAME,MEDIAN SALE PRICE NSA ($),HOMES SOLD
29,2026-07-01,11380,"Andrews, TX metro area",NaN,NaN
300,2026-07-01,22744,"Fort Lauderdale, FL metro area",NaN,NaN
358,2026-07-01,25100,"Guymon, OK metro area",NaN,NaN
490,2026-07-01,30580,"Liberal, KS metro area",NaN,NaN
537,2026-07-01,32500,"Maysville, KY metro area",NaN,NaN
628,2026-07-01,36220,"Odessa, TX metro area",NaN,NaN
667,2026-07-01,37780,"Pecos, TX metro area",NaN,NaN
916,2026-07-01,48500,"West Point, MS metro area",NaN,NaN
975,2026-06-01,11380,"Andrews, TX metro area",NaN,NaN
1246,2026-06-01,22744,"Fort Lauderdale, FL metro area",NaN,NaN
1436,2026-06-01,30580,"Liberal, KS metro area",NaN,NaN
1613,2026-06-01,37780,"Pecos, TX metro area",NaN,NaN
1765,2026-06-01,41260,"St. Marys, PA metro area",NaN,NaN
1921,2026-05-01,11380,"Andrews, TX metro area",NaN,NaN
1977,2026-05-01,13700,"Big Spring, TX metro area",NaN,NaN
2192,2026-05-01,22744,"Fort Lauderdale, FL metro area",NaN,NaN
2382,2026-05-01,30580,"Liberal, KS metro area",NaN,NaN
2407,2026-05-01,31620,"Magnolia, AR metro area",NaN,NaN
2559,2026-05-01,37780,"Pecos, TX metro area",NaN,NaN
2808,2026-05-01,48500,"West Point, MS metro area",NaN,NaN

In [15]:
df_missing_price.shape

(1753, 17)

In [16]:
price_missing = df["MEDIAN SALE PRICE NSA ($)"].isnull()
homes_missing = df["HOMES SOLD"].isnull()

(price_missing == homes_missing).all()

np.True_

In [17]:
print(df["REGION ID"].nunique())
print(df["REGION NAME"].nunique())

946
946

In [18]:
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percent": (df.isnull().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)

missing_summary

                                         missing_count  missing_percent
AVERAGE SALE TO LIST RATIO (%)                    8496             6.47
MEDIAN DAYS ON MARKET (DAYS)                      1884             1.43
PERCENT OFF MARKET IN TWO WEEKS (%)               1870             1.42
PENDING SALES                                     1870             1.42
MONTHS OF SUPPLY                                  1830             1.39
MEDIAN SALE PRICE PER SQ.FT. ($)                  1775             1.35
HOMES SOLD                                        1753             1.33
MEDIAN SALE PRICE NSA ($)                         1753             1.33
MEDIAN NEW LISTING PRICE PER SQ.FT. ($)           1270             0.97
MEDIAN NEW LISTING PRICE ($)                      1244             0.95
NEW LISTINGS                                      1234             0.94
INVENTORY                                          173             0.13
ACTIVE LISTINGS                                     98             0.07
LAST UPDATED                                         0             0.00
REGION ID                                            0             0.00
REGION NAME                                          0             0.00
PERIOD BEGIN                                         0             0.00

In [19]:
df["REGION ID"] = df["REGION ID"].astype(str)

In [20]:
df_census = pd.read_csv("../data/processed/census_metro_income_2024.csv",dtype={"metro_code": str})

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/census_metro_income_2024.csv'

In [ ]:
redfin_ids = set(df["REGION ID"])
census_ids = set(df_census["metro_code"])

matching_ids = redfin_ids & census_ids

print("Redfin regions:", len(redfin_ids))
print("Census metros:", len(census_ids))
print("Direct matches:", len(matching_ids))
print("Census coverage:",round(len(matching_ids) / len(census_ids) * 100, 2),"%")

Redfin regions: 946
Census metros: 393
Direct matches: 368
Census coverage: 93.64 %

In [ ]:
unmatched_census_ids = census_ids - redfin_ids
df_unmatched_census = df_census[
    df_census["metro_code"].isin(unmatched_census_ids)
]

df_unmatched_census[
    ["metro_code", "metro_name"]
].sort_values("metro_name")

    metro_code                                    metro_name
1        10380                                 Aguadilla, PR
12       11200                  Amherst Town-Northampton, MA
17       11640                                   Arecibo, PR
44       14460                Boston-Cambridge-Newton, MA-NH
69       16980               Chicago-Naperville-Elgin, IL-IN
73       17410                                 Cleveland, OH
86       19100               Dallas-Fort Worth-Arlington, TX
96       19820                   Detroit-Warren-Dearborn, MI
144      25020                                   Guayama, PR
183      28450                                   Kenosha, WI
187      28880         Kiryas Joel-Poughkeepsie-Newburgh, NY
207      30500                            Lexington Park, MD
214      31080            Los Angeles-Long Beach-Anaheim, CA
224      32420                                  Mayagüez, PR
229      33100     Miami-Fort Lauderdale-West Palm Beach, FL
253      35620            New York-Newark-Jersey City, NY-NJ
273      37980   Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
279      38660                                     Ponce, PR
316      41860             San Francisco-Oakland-Fremont, CA
318      41980                   San Juan-Bayamón-Caguas, PR
326      42660                   Seattle-Tacoma-Bellevue, WA
335      43640              Slidell-Mandeville-Covington, LA
372      47900  Washington-Arlington-Alexandria, DC-VA-MD-WV
373      47930                         Waterbury-Shelton, CT
382      48680                     Wildwood-The Villages, FL

In [ ]:
ny_redfin = (df[df["REGION NAME"].str.contains("New York|Newark|Nassau|White Plains|Jersey City",case=False,na=False)
            ][["REGION ID", "REGION NAME"]]
    .drop_duplicates()
    .sort_values("REGION NAME")
)

ny_redfin

    REGION ID                   REGION NAME
599     35004  Nassau County, NY metro area
610     35614       New York, NY metro area
611     35084         Newark, NJ metro area

In [ ]:
load_dotenv()
census_api_key = os.getenv("CENSUS_API_KEY")

In [ ]:
url = "https://api.census.gov/data/2024/acs/acs5"

all_divisions = []
division_columns = None

for metro_code in unmatched_census_ids:

    params = {
        "get": "NAME,B19013_001E",
        "for": "metropolitan division:*",
        "in": f"metropolitan statistical area/micropolitan statistical area:{metro_code}",
        "key": census_api_key
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        division_data = response.json()

        if division_columns is None:
            division_columns = division_data[0]

        all_divisions.extend(division_data[1:])

    elif response.status_code == 204:
        continue

    else:
        response.raise_for_status()

In [ ]:
df_divisions = pd.DataFrame(
    all_divisions,
    columns=division_columns
)

df_divisions.head()

,NAME,B19013_001E,metropolitan statistical area/micropolitan statistical area,metropolitan division
0,"Oakland-Fremont-Berkeley, CA Metro Division; S...",128560,41860,36084
1,"San Francisco-San Mateo-Redwood City, CA Metro...",148514,41860,41884
2,"San Rafael, CA Metro Division; San Francisco-O...",149091,41860,42034
3,"Boston, MA Metro Division; Boston-Cambridge-Ne...",111800,14460,14454
4,"Cambridge-Newton-Framingham, MA Metro Division...",120883,14460,15764

In [ ]:
print(df_divisions.shape)
print(df_divisions.columns)

(33, 4)
Index(['NAME', 'B19013_001E',
       'metropolitan statistical area/micropolitan statistical area',
       'metropolitan division'],
      dtype='object')

In [ ]:
df_divisions["metropolitan division"] = (df_divisions["metropolitan division"].astype(str))
division_ids = set(df_divisions["metropolitan division"])

matching_division_ids = division_ids & redfin_ids

print("Census divisions:", len(division_ids))
print("Direct Redfin division matches:", len(matching_division_ids))
print("Division coverage:",round(len(matching_division_ids) / len(division_ids) * 100, 2),"%")

unmatched_division_ids = division_ids - redfin_ids

Census divisions: 33
Direct Redfin division matches: 27
Division coverage: 81.82 %

In [ ]:
df_divisions[df_divisions["metropolitan division"].isin(unmatched_division_ids)][["NAME", "metropolitan division"]]

                                                 NAME metropolitan division
4   Cambridge-Newton-Framingham, MA Metro Division...                 15764
9   Lake County-Porter County-Jasper County, IN Me...                 29414
16  Arlington-Alexandria-Reston, VA-WV Metro Divis...                 11694
18  Washington, DC-MD Metro Division; Washington-A...                 47764
26  Everett, WA Metro Division; Seattle-Tacoma-Bel...                 21794
29  Lakewood-New Brunswick, NJ Metro Division; New...                 29484

In [ ]:
keywords = (
    "Arlington|Alexandria|Washington|"
    "Cambridge|Newton|Framingham|"
    "Lake County|Porter|Jasper|"
    "Lakewood|New Brunswick|Everett"
)

df[df["REGION NAME"].str.contains(keywords,case=False,na=False)
][["REGION ID", "REGION NAME"]].drop_duplicates().sort_values("REGION NAME")

    REGION ID                            REGION NAME
15      10780              Alexandria, LA metro area
16      10820              Alexandria, MN metro area
133     15700               Cambridge, MD metro area
134     15740               Cambridge, OH metro area
420     27530                  Jasper, AL metro area
421     27540                  Jasper, IN metro area
463     29404             Lake County, IL metro area
603     35154           New Brunswick, NJ metro area
900     47920  Washington Court House, OH metro area
901     47894              Washington, DC metro area
902     47780              Washington, IN metro area
903     47820              Washington, NC metro area

In [ ]:
df = df.rename(columns={
    "PERIOD BEGIN": "period_begin",
    "REGION ID": "redfin_region_id",
    "REGION NAME": "region_name",
    "HOMES SOLD": "homes_sold",
    "MEDIAN SALE PRICE NSA ($)": "median_sale_price",
    "MEDIAN DAYS ON MARKET (DAYS)": "median_days_on_market",
    "AVERAGE SALE TO LIST RATIO (%)": "avg_sale_to_list_ratio",
    "NEW LISTINGS": "new_listings",
    "ACTIVE LISTINGS": "active_listings",
    "INVENTORY": "inventory",
    "PENDING SALES": "pending_sales",
    "MEDIAN NEW LISTING PRICE ($)": "median_new_listing_price",
    "MEDIAN NEW LISTING PRICE PER SQ.FT. ($)": "median_new_listing_price_per_sqft",
    "MEDIAN SALE PRICE PER SQ.FT. ($)": "median_sale_price_per_sqft",
    "MONTHS OF SUPPLY": "months_of_supply",
    "PERCENT OFF MARKET IN TWO WEEKS (%)": "percent_off_market_two_weeks"
})

In [ ]:
df["period_begin"] = pd.to_datetime(df["period_begin"])

In [ ]:
df.isnull().sum()

LAST UPDATED                            0
period_begin                            0
redfin_region_id                        0
region_name                             0
homes_sold                           1753
median_sale_price                    1753
median_days_on_market                1884
avg_sale_to_list_ratio               8496
new_listings                         1234
active_listings                        98
inventory                             173
pending_sales                        1870
median_new_listing_price             1244
median_new_listing_price_per_sqft    1270
median_sale_price_per_sqft           1775
months_of_supply                     1830
percent_off_market_two_weeks         1870
dtype: int64

In [ ]:
df=df.drop(columns="LAST UPDATED")

In [ ]:
df = df.dropna(subset=["median_sale_price"]).copy()

In [ ]:
print(df["median_sale_price"].isnull().sum())
print(df["homes_sold"].isnull().sum())

0
0

In [ ]:
# Keep Redfin ID as an identifier
df["redfin_region_id"] = df["redfin_region_id"].astype(str)

# Check duplicates
print("Duplicate rows:", df.duplicated().sum())

# Check core missing values
print(df[["period_begin", "redfin_region_id", "region_name", "median_sale_price"]].isnull().sum())
# Check final shape
print(df.shape)

df.info()

Duplicate rows: 0
period_begin         0
redfin_region_id     0
region_name          0
median_sale_price    0
dtype: int64
(129578, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 129578 entries, 0 to 131329
Data columns (total 16 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   period_begin                       129578 non-null  datetime64[ns]
 1   redfin_region_id                   129578 non-null  object
 2   region_name                        129578 non-null  object
 3   homes_sold                         129578 non-null  float64
 4   median_sale_price                  129578 non-null  float64
 5   median_days_on_market              129447 non-null  float64
 6   avg_sale_to_list_ratio             122835 non-null  float64
 7   new_listings                       128990 non-null  float64
 8   active_listings                    129565 non-null  float64
 9   inventory                          129501 non-null  float64
 10  pending_sales                      129276 non-null  float64
 11  median_new_listing_price           128984 non-null  float64
 12  median_new_listing_price_per_sqft  128968 non-null  float64
 13  median_sale_price_per_sqft         129556 non-null  float64
 14  months_of_supply                   129501 non-null  float64
 15  percent_off_market_two_weeks       129276 non-null  float64
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 16.8+ MB

In [ ]:
df.duplicated(subset=["period_begin", "redfin_region_id"]).sum()

np.int64(0)

In [ ]:
df=df.sort_values(["period_begin","redfin_region_id"]).reset_index(drop=True)

In [ ]:
df.to_csv("../data/processed/redfin_monthly_housing.csv",index=False)

In [ ]:
df["median_days_on_market"] = pd.to_numeric(df["median_days_on_market"],errors="coerce")

In [ ]:
df["homes_sold"]=df["homes_sold"].astype(int)
df["median_days_on_market"] = (df["median_days_on_market"].astype("Int64"))

In [ ]:
df.head()

,period_begin,redfin_region_id,region_name,homes_sold,median_sale_price,median_days_on_market,avg_sale_to_list_ratio,new_listings,active_listings,inventory,pending_sales,median_new_listing_price,median_new_listing_price_per_sqft,median_sale_price_per_sqft,months_of_supply,percent_off_market_two_weeks
0,2015-01-01,10100,"Aberdeen, SD metro area",17,132000.0,99,93.58,16.0,118.0,102.0,17.0,115000.0,88.90,110.58,6.2,0.00
1,2015-01-01,10140,"Aberdeen, WA metro area",55,80000.0,136,92.95,88.0,573.0,478.0,99.0,154000.0,99.15,61.94,9.0,7.07
2,2015-01-01,10180,"Abilene, TX metro area",122,132450.0,59,96.21,165.0,667.0,523.0,171.0,132500.0,80.49,82.10,4.4,30.99
3,2015-01-01,10220,"Ada, OK metro area",1,64900.0,<NA>,92.85,20.0,75.0,75.0,1.0,89250.0,62.95,47.51,77.5,0.00
4,2015-01-01,10300,"Adrian, MI metro area",61,85000.0,117,95.58,105.0,801.0,705.0,58.0,114900.0,70.82,60.25,11.9,0.00

In [ ]:
optional_nonnegative = [
        "median_days_on_market",
        "new_listings",
        "active_listings",
        "inventory",
        "pending_sales",
        "median_new_listing_price",
        "median_new_listing_price_per_sqft",
        "median_sale_price_per_sqft",
        "months_of_supply"
    ]

for column in optional_nonnegative:
    print(column, df[column].min())

median_days_on_market 0
new_listings -753.0
active_listings 1.0
inventory 1.0
pending_sales 1.0
median_new_listing_price 1000.0
median_new_listing_price_per_sqft 0.09
median_sale_price_per_sqft 0.0
months_of_supply 0.0

In [ ]:
negative_new_listings = df[
    df["new_listings"] < 0
][
    ["period_begin", "redfin_region_id", "region_name", "new_listings"]
]

print("Negative values:", len(negative_new_listings))

negative_new_listings.head(20)

Negative values: 1

      period_begin redfin_region_id              region_name  new_listings
58812   2020-04-01            35614  New York, NY metro area        -753.0

In [ ]:
df.loc[df["new_listings"] < 0, "new_listings"] = pd.NA

In [ ]:
(df["new_listings"].dropna() < 0).sum()

np.int64(0)

In [21]:
df["percent_off_market_two_weeks"].head()

KeyError: 'percent_off_market_two_weeks'

In [2]:
import pandas as pd

df_redfin = pd.read_csv("../data/processed/redfin_monthly_housing_integrated.csv")

print("CSV rows:", len(df_redfin))

CSV rows: 52464

In [3]:
print(
    "Duplicate primary keys:",
    df_redfin.duplicated(
        subset=["geo_id", "period_begin"]
    ).sum()
)

print(df_redfin.isna().sum())

Duplicate primary keys: 0
period_begin                            0
redfin_region_id                        0
region_name                             0
homes_sold                              0
median_sale_price                       0
median_days_on_market                   1
avg_sale_to_list_ratio               1703
new_listings                            8
active_listings                         0
inventory                               1
pending_sales                          36
median_new_listing_price                8
median_new_listing_price_per_sqft       8
median_sale_price_per_sqft              0
months_of_supply                        1
percent_off_market_two_weeks           36
geo_id                                  0
dtype: int64

In [4]:
mysql_columns = [
    "geo_id",
    "period_begin",
    "redfin_region_id",
    "median_sale_price",
    "median_sale_price_per_sqft",
    "homes_sold",
    "inventory",
    "median_days_on_market",
    "months_of_supply",
    "percent_off_market_two_weeks"
]

rows_with_missing = df_redfin[
    df_redfin[mysql_columns].isna().any(axis=1)
]

print("Rows with missing MySQL values:", len(rows_with_missing))

rows_with_missing[
    [
        "geo_id",
        "period_begin",
        "region_name",
        "inventory",
        "median_days_on_market",
        "months_of_supply",
        "percent_off_market_two_weeks"
    ]
]

Rows with missing MySQL values: 38

,geo_id,period_begin,region_name,inventory,median_days_on_market,months_of_supply,percent_off_market_two_weeks
20487,25620,2020-04-01,"Hattiesburg, MS metro area",439.0,33.0,3.5,NaN
31950,33740,2015-01-01,"Monroe, LA metro area",487.0,458.0,38.7,NaN
31951,33740,2015-02-01,"Monroe, LA metro area",488.0,892.0,41.4,NaN
31952,33740,2015-03-01,"Monroe, LA metro area",475.0,918.0,19.6,NaN
31960,33740,2015-11-01,"Monroe, LA metro area",480.0,1140.0,19.2,NaN
31962,33740,2016-01-01,"Monroe, LA metro area",470.0,1003.0,37.4,NaN
31963,33740,2016-02-01,"Monroe, LA metro area",484.0,1016.0,36.0,NaN
31964,33740,2016-03-01,"Monroe, LA metro area",481.0,654.0,55.2,NaN
31966,33740,2016-05-01,"Monroe, LA metro area",484.0,1432.0,20.0,NaN
31967,33740,2016-06-01,"Monroe, LA metro area",486.0,554.0,13.1,NaN
31968,33740,2016-07-01,"Monroe, LA metro area",458.0,950.0,26.3,NaN
31969,33740,2016-08-01,"Monroe, LA metro area",448.0,973.0,14.5,NaN
31972,33740,2016-11-01,"Monroe, LA metro area",437.0,1461.0,15.6,NaN
31974,33740,2017-01-01,"Monroe, LA metro area",436.0,623.0,30.0,NaN
31975,33740,2017-02-01,"Monroe, LA metro area",462.0,766.0,71.9,NaN
31976,33740,2017-03-01,"Monroe, LA metro area",469.0,1220.0,17.9,NaN
31977,33740,2017-04-01,"Monroe, LA metro area",483.0,1125.0,16.7,NaN
31979,33740,2017-06-01,"Monroe, LA metro area",486.0,980.0,15.2,NaN
31984,33740,2017-11-01,"Monroe, LA metro area",572.0,590.0,22.0,NaN
31987,33740,2018-02-01,"Monroe, LA metro area",552.0,640.0,42.9,NaN
31988,33740,2018-03-01,"Monroe, LA metro area",562.0,375.0,24.2,NaN
31989,33740,2018-04-01,"Monroe, LA metro area",562.0,710.0,18.1,NaN
31991,33740,2018-06-01,"Monroe, LA metro area",586.0,699.0,15.8,NaN
31992,33740,2018-07-01,"Monroe, LA metro area",607.0,843.0,23.2,NaN
31993,33740,2018-08-01,"Monroe, LA metro area",610.0,682.0,19.1,NaN
32002,33740,2019-05-01,"Monroe, LA metro area",701.0,1429.0,20.1,NaN
32003,33740,2019-06-01,"Monroe, LA metro area",707.0,620.0,16.4,NaN
32006,33740,2019-09-01,"Monroe, LA metro area",818.0,1511.0,29.2,NaN
32008,33740,2019-11-01,"Monroe, LA metro area",914.0,850.0,39.7,NaN
44459,43340,2016-03-01,"Shreveport, LA metro area",3.0,159.0,3.1,NaN
44461,43340,2016-12-01,"Shreveport, LA metro area",13.0,131.0,13.4,NaN
44464,43340,2017-04-01,"Shreveport, LA metro area",4.0,174.0,4.0,NaN
44467,43340,2017-11-01,"Shreveport, LA metro area",9.0,43.0,9.0,NaN
44474,43340,2018-11-01,"Shreveport, LA metro area",8.0,854.0,4.0,NaN
44481,43340,2019-12-01,"Shreveport, LA metro area",30.0,13.0,31.0,NaN
47060,45500,2015-05-01,"Texarkana, TX metro area",NaN,277.0,NaN,0.0
48719,46660,2015-08-01,"Valdosta, GA metro area",35.0,NaN,36.2,0.0
49962,47940,2015-01-01,"Waterloo, IA metro area",62.0,30.0,64.1,NaN

In [5]:
print(
    df_redfin["percent_off_market_two_weeks"].min(),
    df_redfin["percent_off_market_two_weeks"].max()
)

print(
    df_redfin["months_of_supply"].min(),
    df_redfin["months_of_supply"].max()
)

print(
    df_redfin["median_sale_price"].max()
)

print(
    df_redfin["median_sale_price_per_sqft"].max()
)

-7.57 100.0
0.1 891.1
1777500.0
1084.44

In [6]:
print(
    "Rows equal to 100:",
    (df_redfin["percent_off_market_two_weeks"] == 100).sum()
)

Rows equal to 100: 3

In [7]:
negative_percent = df_redfin[
    df_redfin["percent_off_market_two_weeks"] < 0
]

print("Negative values:", len(negative_percent))

negative_percent[
    [
        "geo_id",
        "period_begin",
        "region_name",
        "percent_off_market_two_weeks"
    ]
]

Negative values: 57

,geo_id,period_begin,region_name,percent_off_market_two_weeks
558,10580,2015-03-01,"Albany, NY metro area",-0.30
559,10580,2015-04-01,"Albany, NY metro area",-0.83
560,10580,2015-05-01,"Albany, NY metro area",-1.30
696,10740,2015-02-01,"Albuquerque, NM metro area",-0.11
697,10740,2015-03-01,"Albuquerque, NM metro area",-0.40
4867,13820,2015-03-01,"Birmingham, AL metro area",-0.42
5561,14260,2015-03-01,"Boise City, ID metro area",-0.27
5566,14260,2015-08-01,"Boise City, ID metro area",-0.69
5574,14260,2016-04-01,"Boise City, ID metro area",-1.57
5575,14260,2016-05-01,"Boise City, ID metro area",-2.73
5586,14260,2017-04-01,"Boise City, ID metro area",-7.57
6407,14860,2016-03-01,"Bridgeport, CT metro area",-0.36
6408,14860,2016-04-01,"Bridgeport, CT metro area",-0.46
6418,14860,2017-02-01,"Bridgeport, CT metro area",-1.05
6419,14860,2017-03-01,"Bridgeport, CT metro area",-0.73
6420,14860,2017-04-01,"Bridgeport, CT metro area",-1.12
6421,14860,2017-05-01,"Bridgeport, CT metro area",-0.72
6812,15380,2015-03-01,"Buffalo, NY metro area",-0.83
6813,15380,2015-04-01,"Buffalo, NY metro area",-2.14
9448,17140,2015-03-01,"Cincinnati, OH metro area",-0.07
10838,18140,2015-03-01,"Columbus, OH metro area",-1.65
10839,18140,2015-04-01,"Columbus, OH metro area",-3.31
11950,19430,2015-03-01,"Dayton, OH metro area",-0.73
11951,19430,2015-04-01,"Dayton, OH metro area",-0.07
11952,19430,2015-05-01,"Dayton, OH metro area",-0.71
12670,19780,2017-04-01,"Des Moines, IA metro area",-0.05
12671,19780,2017-05-01,"Des Moines, IA metro area",-0.71
18341,24340,2015-03-01,"Grand Rapids, MI metro area",-1.05
18342,24340,2015-04-01,"Grand Rapids, MI metro area",-1.38
18343,24340,2015-05-01,"Grand Rapids, MI metro area",-1.14
19036,24660,2015-03-01,"Greensboro, NC metro area",-0.33
24457,28140,2015-03-01,"Kansas City, MO metro area",-1.85
24458,28140,2015-04-01,"Kansas City, MO metro area",-2.25
24459,28140,2015-05-01,"Kansas City, MO metro area",-1.91
24460,28140,2015-06-01,"Kansas City, MO metro area",-1.21
28061,30780,2015-03-01,"Little Rock, AR metro area",-0.10
28062,30780,2015-04-01,"Little Rock, AR metro area",-0.48
28756,31140,2015-03-01,"Louisville, KY metro area",-2.69
30018,32580,2016-02-01,"McAllen, TX metro area",-0.24
30039,32580,2017-11-01,"McAllen, TX metro area",-0.02
33642,35300,2017-01-01,"New Haven, CT metro area",-0.19
33643,35300,2017-02-01,"New Haven, CT metro area",-0.42
33644,35300,2017-03-01,"New Haven, CT metro area",-0.81
33645,35300,2017-04-01,"New Haven, CT metro area",-0.71
33959,35614,2020-04-01,"New York, NY metro area",-1.86
34867,36420,2015-03-01,"Oklahoma City, OK metro area",-1.58
37089,38300,2015-03-01,"Pittsburgh, PA metro area",-1.62
40007,40380,2015-02-01,"Rochester, NY metro area",-0.06
40008,40380,2015-03-01,"Rochester, NY metro area",-1.17
40009,40380,2015-04-01,"Rochester, NY metro area",-2.90
41814,41620,2015-02-01,"Salt Lake City, UT metro area",-0.14
41815,41620,2015-03-01,"Salt Lake City, UT metro area",-2.77
41816,41620,2015-04-01,"Salt Lake City, UT metro area",-3.90
41817,41620,2015-05-01,"Salt Lake City, UT metro area",-3.00
41818,41620,2015-06-01,"Salt Lake City, UT metro area",-0.83
47881,46140,2015-04-01,"Tulsa, OK metro area",-0.44
47882,46140,2015-05-01,"Tulsa, OK metro area",-0.70

In [8]:
problem_rows = df_redfin[
    df_redfin[mysql_columns].isna().any(axis=1)
    |
    (df_redfin["percent_off_market_two_weeks"] == 100)
]

print("Total problem rows:", len(problem_rows))

Total problem rows: 41

In [9]:
print(
    "Above 100:",
    (df_redfin["percent_off_market_two_weeks"] > 100).sum()
)

print(
    df_redfin["percent_off_market_two_weeks"].describe()
)

Above 100: 0
count    52428.000000
mean        23.960518
std         20.136204
min         -7.570000
25%          3.037500
50%         23.290000
75%         39.440000
max        100.000000
Name: percent_off_market_two_weeks, dtype: float64

In [10]:
mysql_columns = [
    "geo_id",
    "period_begin",
    "redfin_region_id",
    "median_sale_price",
    "median_sale_price_per_sqft",
    "homes_sold",
    "inventory",
    "median_days_on_market",
    "months_of_supply",
    "percent_off_market_two_weeks"
]

df_mysql = df_redfin[mysql_columns].copy()

df_mysql.to_csv("../data/processed/redfin_mysql_ready.csv",index=False,na_rep="\\N")

In [1]:
from pathlib import Path

print(Path("../data/processed/redfin_mysql_ready.csv").resolve())

C:\Users\abaho\source\Housing-Market-Intelligence-Platform\data\processed\redfin_mysql_ready.csv

In [3]:
import pandas as pd

df_redfin = pd.read_csv("../data/processed/redfin_monthly_housing.csv")

print("Negative values:",(df_redfin["percent_off_market_two_weeks"] < 0).sum())

print("Missing values:",df_redfin["percent_off_market_two_weeks"].isna().sum())

Negative values: 0
Missing values: 360

In [ ]:
df_redfin = pd.read_csv("../data/processed/redfin_monthly_housing_integrated.csv")

print("Negative:",(df_redfin["percent_off_market_two_weeks"] < 0).sum())

print("Missing:",df_redfin["percent_off_market_two_weeks"].isna().sum())

Negative: 0
Missing: 93

In [5]:
mysql_columns = [
    "geo_id",
    "period_begin",
    "redfin_region_id",
    "median_sale_price",
    "median_sale_price_per_sqft",
    "homes_sold",
    "inventory",
    "median_days_on_market",
    "months_of_supply",
    "percent_off_market_two_weeks"
]

df_mysql = df_redfin[mysql_columns].copy()

df_mysql.to_csv("../data/processed/redfin_mysql_ready.csv",index=False,na_rep="\\N")