In [1]:
import pandas as pd

df_bridge = pd.read_csv("../data/processed/geography_bridge.csv",
    dtype={
        "geo_id": str,
        "redfin_region_id": str,
        "zillow_region_id": str
    }
)
df_bridge.head()

,redfin_region_id,zillow_region_id,geo_id,region_name_redfin,region_name_zillow,geo_name,geography_type,parent_metro_code
0,10180,394299,10180,"Abilene, TX metro area","Abilene, TX","Abilene, TX",metro,NaN
1,10420,394304,10420,"Akron, OH metro area","Akron, OH","Akron, OH",metro,NaN
2,10500,394306,10500,"Albany, GA metro area","Albany, GA","Albany, GA",metro,NaN
3,10540,394307,10540,"Albany, OR metro area","Albany, OR","Albany, OR",metro,NaN
4,10580,394308,10580,"Albany, NY metro area","Albany, NY","Albany-Schenectady-Troy, NY",metro,NaN

In [2]:
df_redfin = pd.read_csv("../data/processed/redfin_monthly_housing.csv",dtype={"redfin_region_id": str})

In [3]:
df_redfin_test = df_redfin.merge(df_bridge[["geo_id", "redfin_region_id"]],
    on="redfin_region_id",
    how="inner",
    validate="many_to_one"
)

In [4]:
df_zillow = pd.read_csv("../data/processed/zillow_monthly_rent.csv",dtype={"zillow_region_id": str})

df_zillow_test = df_zillow.merge(df_bridge[["geo_id", "zillow_region_id"]],
    on="zillow_region_id",
    how="inner",
    validate="many_to_one"
)

In [5]:
df_redfin_test.head()

,period_begin,redfin_region_id,region_name,homes_sold,median_sale_price,median_days_on_market,avg_sale_to_list_ratio,new_listings,active_listings,inventory,pending_sales,median_new_listing_price,median_new_listing_price_per_sqft,median_sale_price_per_sqft,months_of_supply,percent_off_market_two_weeks,geo_id
0,2015-01-01,10180,"Abilene, TX metro area",122,132450.0,59.0,96.21,165.0,667.0,523.0,171.0,132500.0,80.49,82.10,4.4,30.99,10180
1,2015-02-01,10180,"Abilene, TX metro area",113,138500.0,58.0,96.55,155.0,672.0,499.0,179.0,149500.0,88.11,83.23,4.1,32.40,10180
2,2015-03-01,10180,"Abilene, TX metro area",163,140000.0,40.0,97.08,213.0,706.0,499.0,211.0,155000.0,86.40,87.03,3.2,38.86,10180
3,2015-04-01,10180,"Abilene, TX metro area",167,134035.0,41.0,97.17,243.0,737.0,528.0,216.0,159950.0,92.26,82.61,3.2,44.44,10180
4,2015-05-01,10180,"Abilene, TX metro area",158,146250.0,32.0,97.53,243.0,766.0,585.0,201.0,147900.0,83.68,78.34,3.8,34.33,10180

In [10]:
df_zillow_test.head(10)

  zillow_region_id  region_name state_name        date    rent geo_id
0           394299  Abilene, TX         TX  2015-01-01  820.34  10180
1           394299  Abilene, TX         TX  2015-02-01  822.50  10180
2           394299  Abilene, TX         TX  2015-03-01  820.97  10180
3           394299  Abilene, TX         TX  2015-04-01  821.40  10180
4           394299  Abilene, TX         TX  2015-05-01  829.59  10180
5           394299  Abilene, TX         TX  2015-06-01  837.12  10180
6           394299  Abilene, TX         TX  2015-07-01  839.13  10180
7           394299  Abilene, TX         TX  2015-08-01  836.70  10180
8           394299  Abilene, TX         TX  2015-09-01  835.08  10180
9           394299  Abilene, TX         TX  2015-10-01  835.42  10180

In [7]:
df_redfin_test.isna().sum()

period_begin                            0
redfin_region_id                        0
region_name                             0
homes_sold                              0
median_sale_price                       0
median_days_on_market                   1
avg_sale_to_list_ratio               1703
new_listings                            8
active_listings                         0
inventory                               1
pending_sales                          36
median_new_listing_price                8
median_new_listing_price_per_sqft       8
median_sale_price_per_sqft              0
months_of_supply                        1
percent_off_market_two_weeks           36
geo_id                                  0
dtype: int64

In [8]:
df_zillow_test.isna().sum()

zillow_region_id    0
region_name         0
state_name          0
date                0
rent                0
geo_id              0
dtype: int64

In [9]:
df_redfin_test[["geo_id", "redfin_region_id", "region_name"]].drop_duplicates()

      geo_id redfin_region_id                region_name
0      10180            10180     Abilene, TX metro area
139    10420            10420       Akron, OH metro area
278    10500            10500      Albany, GA metro area
417    10540            10540      Albany, OR metro area
556    10580            10580      Albany, NY metro area
...      ...              ...                        ...
51769  49420            49420      Yakima, WA metro area
51908  49620            49620        York, PA metro area
52047  49660            49660  Youngstown, OH metro area
52186  49700            49700   Yuba City, CA metro area
52325  49740            49740        Yuma, AZ metro area

[378 rows x 3 columns]

In [11]:
print("Original Redfin rows:", len(df_redfin))
print("Integrated Redfin rows:", len(df_redfin_test))

print("Original Zillow rows:", len(df_zillow))
print("Integrated Zillow rows:", len(df_zillow_test))

Original Redfin rows: 129578
Integrated Redfin rows: 52464
Original Zillow rows: 52629
Integrated Zillow rows: 42235

In [12]:
print("Bridge geographies:", len(df_bridge))
print("Original Redfin geographies:",df_redfin["redfin_region_id"].nunique())
print("Integrated Redfin geographies:",df_redfin_test["redfin_region_id"].nunique())
print("Original Zillow geographies:",df_zillow["zillow_region_id"].nunique())
print("Integrated Zillow geographies:",df_zillow_test["zillow_region_id"].nunique())
print("Redfin unique geo_ids:",df_redfin_test["geo_id"].nunique())
print("Zillow unique geo_ids:",df_zillow_test["geo_id"].nunique())

Bridge geographies: 378
Original Redfin geographies: 946
Integrated Redfin geographies: 378
Original Zillow geographies: 751
Integrated Zillow geographies: 378
Redfin unique geo_ids: 378
Zillow unique geo_ids: 378

In [14]:
df_census = pd.read_csv("../data/processed/census_geography_income_2024.csv",dtype={"geo_id": str})

df_redfin["redfin_region_id"] = (df_redfin["redfin_region_id"].astype(str))

redfin_geo = (df_redfin[["redfin_region_id", "region_name"]].drop_duplicates())

census_geo = (df_census[["geo_id", "geo_name", "geography_type"]].drop_duplicates())

redfin_census = redfin_geo.merge(
    census_geo,
    left_on="redfin_region_id",
    right_on="geo_id",
    how="inner",
    validate="one_to_one"
)

print("Redfin/Census compatible geographies:",len(redfin_census))

Redfin/Census compatible geographies: 395

In [15]:
redfin_census_ids = set(redfin_census["redfin_region_id"])

final_bridge_ids = set(df_bridge["redfin_region_id"])

not_in_final_bridge = (redfin_census_ids - final_bridge_ids)

print("Redfin/Census markets not in final bridge:",len(not_in_final_bridge))

Redfin/Census markets not in final bridge: 17

In [ ]:
redfin_census[
    redfin_census["redfin_region_id"].isin(not_in_final_bridge)
][
    [
        "redfin_region_id",
        "region_name",
        "geo_name",
        "geography_type"
    ]
].sort_values("region_name")

,redfin_region_id,region_name,geo_name,geography_type
11,11244,"Anaheim, CA metro area","Anaheim-Santa Ana-Irvine, CA",division
53,15804,"Camden, NJ metro area","Camden, NJ",division
103,20994,"Elgin, IL metro area","Elgin, IL",division
123,22744,"Fort Lauderdale, FL metro area","Fort Lauderdale-Pompano Beach-Sunrise, FL",division
126,23104,"Fort Worth, TX metro area","Fort Worth-Arlington-Grapevine, TX",division
127,23224,"Frederick, MD metro area","Frederick-Gaithersburg-Bethesda, MD",division
193,29404,"Lake County, IL metro area","Lake County, IL",division
240,33874,"Montgomery County, PA metro area","Montgomery County-Bucks County-Chester County, PA",division
250,35004,"Nassau County, NY metro area","Nassau County-Suffolk County, NY",division
251,35084,"Newark, NJ metro area","Newark, NJ",division
258,36084,"Oakland, CA metro area","Oakland-Fremont-Berkeley, CA",division
301,40484,"Rockingham County, NH metro area","Rockingham County-Strafford County, NH",division
321,42034,"San Rafael, CA metro area","San Rafael, CA",division
349,45104,"Tacoma, WA metro area","Tacoma-Lakewood, WA",division
374,47664,"Warren, MI metro area","Warren-Troy-Farmington Hills, MI",division
380,48424,"West Palm Beach, FL metro area","West Palm Beach-Boca Raton-Delray Beach, FL",division
385,48864,"Wilmington, DE metro area","Wilmington, DE-MD-NJ",division